### ISSUE TITLE
Having trouble compiling on Archlinux

### ISSUE THREAD

**Issue by gtmanfred** [gewalker/plex-linux#14]
I have been told that it would require a patch for libpng 16?
any help would be apreciated, currently i have libpng 1.5.9-1

make -C xbmc/lib/cximage-6.0
make[1]: Entering directory `/home/daniel/build/plex/src/laika-build/xbmc/lib/cximage-6.0'
make -C CxImage ARCH=x86_64-linux
make[2]: Entering directory`/home/daniel/build/plex/src/laika-build/xbmc/lib/cximage-6.0/CxImage'
g++ -MD -c -fPIC -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -g -D_DEBUG -Wall -O2 -D_DLL -DXBMC -D_LINUX -D_FILE_DEFINED -D__STDC_CONSTANT_MACROS -DBIN_INSTALL_PATH="\"/usr/lib/xbmc\"" -DINSTALL_PATH="\"/usr/share/xbmc\"" -DHAS_SDL_JOYSTICK -D'GIT_REV="a4d6ec9"' -DHAVE_CONFIG_H  -D_GNU_SOURCE=1 -D_REENTRANT -I/home/daniel/build/plex/src/laika-build -I/usr/include/SDL -I/usr/include/alsa -I/usr/include/dbus-1.0 -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/libpng15 -I/usr/include/lzo -I/usr/include/mysql -I/usr/lib/dbus-1.0/include ximaenc.cpp -o ximaenc.o
In file included from ximaenc.cpp:17:0:
ximapng.h: In static member function ‘static void CxImagePNG::user_error_fn(png_structp, png_const_charp)’:
ximapng.h:72:25: error: invalid use of incomplete type ‘png_struct {aka struct png_struct_def}’
/usr/include/libpng15/png.h:855:16: error: forward declaration of ‘png_struct {aka struct png_struct_def}’
ximapng.h:73:18: error: invalid use of incomplete type ‘png_struct {aka struct png_struct_def}’
/usr/include/libpng15/png.h:855:16: error: forward declaration of ‘png_struct {aka struct png_struct_def}’
ximaenc.cpp: In member function ‘bool CxImage::Load(const char_, DWORD, int&, int&)’:
ximaenc.cpp:512:6: warning: unused variable ‘iWidthSave’ [-Wunused-variable]
ximaenc.cpp:513:6: warning: unused variable ‘iHeightSave’ [-Wunused-variable]
ximaenc.cpp: In member function ‘bool CxImage::CheckFormat(BYTE_, DWORD, DWORD)’:
ximaenc.cpp:1114:28: warning: NULL used in arithmetic [-Wpointer-arith]
make[2]: **\* [ximaenc.o] Error 1
make[2]: Leaving directory `/home/daniel/build/plex/src/laika-build/xbmc/lib/cximage-6.0/CxImage'
make[1]: *** [CxImage/cximage.a] Error 2
make[1]: Leaving directory`/home/daniel/build/plex/src/laika-build/xbmc/lib/cximage-6.0'
make: **\* [imagelib] Error 2

**Comment by gest01** [comment]
hi.. i have the same error as well. Any solutions yet?

**Comment by wbagdon** [comment]
I've gotten through the build using libpng12 or libpng14 but running plex with either just results in a black screen that can't be exited.  Here is the error in the debug, definitely a PNG issue...

17:39:53 T:139859094009920 M: 0%   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/ImageLib-x86_64-linux.so)
17:39:53 T:139859094009920 M: 0%   DEBUG: Loading: /usr/local/lib/xbmc/system/ImageLib-x86_64-linux.so
17:39:53 T:139859094009920 M: 0%    INFO:   msg: PICTURE::LoadImage: Unable to open image: special://xbmc/media/icon.png Error:Failed to create PNG structure (2)
17:39:53 T:139859094009920 M: 0%   ERROR: Texture manager unable to load file: special://xbmc/media/icon.png

**Comment by wbagdon** [comment]
Build with libpng15 by replacing the ximapng.(cpp/h) with compatible ones from this branch https://github.com/Boudin/xbmc/tree/master/lib/cximage-6.0/CxImage

PMC will launch after editing FEH.py putting parenthesis around print(errorLine)

**Comment by gtmanfred** [comment]
success https://aur.archlinux.org/packages.php?ID=57498
thank you
