### ISSUE TITLE
libmysqlclient and libsmbclient

### ISSUE THREAD

**Issue by h0lzi** [gewalker/plex-linux#3]
is this still needed somewhere is the plex code or can it be removed form autoconf? It probably still is in the code but thought I just ask :)

**Comment by gewalker** [comment]
h0lzi:  Not sure.  I based the Makefile for the Linux project on the objects which Plex compiles on OSX.  I suspect there's actually a lot of cleanup of this sort which we can do.  Elan:  thoughts?

**Comment by h0lzi** [comment]
they are still used in the code. So for now they are still needed.

**Comment by gewalker** [comment]
Closing this issue accordingly, then.
