### ISSUE TITLE
linking problem during ffmpeg compile.

### ISSUE THREAD

**Issue by h0lzi** [gewalker/plex-linux#4]
It kind of is part of the old ticket :)
During ffmpeg compile it fails:
LD  libavcodec/libavcodec.so.53
/usr/bin/ld: cannot find -lavutil
collect2: ld returned 1 exit status
make: **\* [libavcodec/libavcodec.so.53] Error 1

So some include flag for the linker is broken to look for the lib in build source.

Thats why the libav*-dev packages ended up in the needed package list.
This is wrong though as you link with an "older" installed version instead of the new build one.
I'm not fast at fixing this so maybe someone is quicker to find whats missing. 

We might want to use some new configure options for ffmpeg too:
See newest xbmc configure.in script:
https://github.com/xbmc/xbmc/blob/master/configure.in#L2058

**Comment by RustyDust** [comment]
Have you initialized the submodules doing a "git submodule update --init" before compiling? This will pull the latest ffmpeg used by PMC.

**Comment by h0lzi** [comment]
Yes. Without it the ffmpeg dir would be emtpy so I had to figure out the git submodule stuff :) First new git thing I learned today.

**Comment by gewalker** [comment]
Thanks h0lzi.  I'll look over that link tonight and see about integrating the updated configure or whatever elements of it are useful.

**Comment by h0lzi** [comment]
ok sorry for the noise. I did share the filesystem with vmware tools. And the linker somehow was not able to follow a symlink. No clue why. Anyway works now.
